
development:
  adapter: postgresql
  encoding: unicode
  database: lean_development
  pool: 5
  username: ricoru
  password: '12345678'
  host: '192.168.0.11'
  port: 5432


test:
  adapter: postgresql
  encoding: unicode
  database: lean_test
  pool: 5
  username: ricoru
  password: '12345678'
  host: '192.168.0.11'
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: lean_production
  pool: 5
  username: ricoru
  password: '12345678'
  host: '192.168.0.11'
  port: 5432
